package files;

import package1.BaseClass;

public class payload extends BaseClass{
	
	public static String createCn() {
		
		
		return "{\n"
				+ "    \"id\": null,\n"
				+ "    \"cnoteType\": \"NORMAL\",\n"
				+ "    \"cnote\": \""+cNote+"\",\n"
				+ "    \"clientCode\": \"UNIBC\",\n"
				+ "    \"serviceType\": \"ZOOM\",\n"
				+ "    \"gstNumber\": null,\n"
				+ "    \"fromPinCode\": \"110001\",\n"
				+ "    \"toPinCode\": \"110033\",\n"
				+ "    \"totalBoxes\": \"1\",\n"
				+ "    \"weight\": \"1\",\n"
				+ "    \"volume\": null,\n"
				+ "    \"value\": null,\n"
				+ "    \"bookingDateTime\": 1645163933000,\n"
				+ "    \"consignorAddress\": \"test\",\n"
				+ "    \"consignorAddressId\": "+consignorId+",\n"
				+ "    \"consignorEmail\": \"testunibic@gmail.com\",\n"
				+ "    \"consignorPhone\": \"9971639104\",\n"
				+ "    \"consigneeAddress\": \"sdfv dvervev sc\",\n"
				+ "    \"consigneeAddressId\": "+consigneeId+",\n"
				+ "    \"consigneeEmail\": null,\n"
				+ "    \"consigneePhone\": \"12313131313\",\n"
				+ "    \"contents\": \"Chemicals\",\n"
				+ "    \"consignorName\": \"test\",\n"
				+ "    \"consigneeName\": \"Rivigo costumer\",\n"
				+ "    \"consignmentDocumentDtoList\": [\n"
				+ "        {\n"
				+ "            \"document\": \"GST Invoice / Delivery Challan\",\n"
				+ "            \"status\": \"NOT_PICKED_UP\",\n"
				+ "            \"minInvoiceValue\": null,\n"
				+ "            \"documentType\": \"GSTIN number\",\n"
				+ "            \"order\": 99\n"
				+ "        },\n"
				+ "        {\n"
				+ "            \"document\": \"CN consignee copy\",\n"
				+ "            \"status\": \"NOT_PICKED_UP\",\n"
				+ "            \"minInvoiceValue\": null,\n"
				+ "            \"order\": 2\n"
				+ "        },\n"
				+ "        {\n"
				+ "            \"document\": \"CN POD copy\",\n"
				+ "            \"status\": \"NOT_PICKED_UP\",\n"
				+ "            \"minInvoiceValue\": null,\n"
				+ "            \"order\": 1\n"
				+ "        }\n"
				+ "    ],\n"
				+ "    \"packing\": \"Bundle\",\n"
				+ "    \"barcodeType\": \"PRE_PRINTED\",\n"
				+ "    \"barcodes\": [\n"
				+ "        "+cNote+""
				+ "    ],\n"
				+ "    \"isDacc\": null,\n"
				+ "    \"invoices\": [\n"
				+ "        {\n"
				+ "            \"invoiceId\": null,\n"
				+ "            \"invoiceNo\": \"1\",\n"
				+ "            \"invoiceValue\": \"1\",\n"
				+ "            \"eWaybillNumber\": \"\",\n"
				+ "            \"hsnCodes\": null\n"
				+ "        }\n"
				+ "    ],\n"
				+ "    \"volumeDetails\": [\n"
				+ "        {\n"
				+ "            \"unit\": \"IN\",\n"
				+ "            \"breadth\": \"1\",\n"
				+ "            \"height\": \"1\",\n"
				+ "            \"numberOfBoxes\": \"1\",\n"
				+ "            \"length\": \"1\",\n"
				+ "            \"volume\": 0.0006\n"
				+ "        }\n"
				+ "    ],\n"
				+ "    \"valueAddedServicesDTO\": null,\n"
				+ "    \"paymentDetailsDTO\": null,\n"
				+ "    \"gstDetailsDTO\": null,\n"
				+ "    \"taxId\": null,\n"
				+ "    \"taxIdType\": null,\n"
				+ "    \"trackerDTO\": {\n"
				+ "        \"deviceIdType\": \"IP\",\n"
				+ "        \"deviceType\": \"ZOOM_OPS\"\n"
				+ "    },\n"
				+ "    \"openPopupTime\": 1573037386291,\n"
				+ "    \"allIssuesResolved\": true,\n"
				+ "    \"billingEntity\": \"UNIBIC FOODS INDIA PVT LTD.\",\n"
				+ "    \"vehicleNumber\": \"HR55V5525\",\n"
				+ "    \"consignmentCodDodDTO\": null,\n"
				+ "    \"deliveryType\": \"NORMAL\",\n"
				+ "    \"completionStatus\": \"COMPLETE\"\n"
				+ "}";
	}
	public static String createRetailCn() {
		return "{\n"
				+ "    \"id\": null,\n"
				+ "    \"cnoteType\": \"RETAIL\",\n"
				+ "    \"cnote\": \"3000037386\",\n"
				+ "    \"clientCode\": \"ZRETL\",\n"
				+ "    \"serviceType\": \"ZOOM\",\n"
				+ "    \"gstNumber\": null,\n"
				+ "    \"fromPinCode\": \"110021\",\n"
				+ "    \"toPinCode\": \"110033\",\n"
				+ "    \"totalBoxes\": \"1\",\n"
				+ "    \"weight\": \"10\",\n"
				+ "    \"volume\": null,\n"
				+ "    \"value\": null,\n"
				+ "    \"bookingDateTime\": 1645163933000,\n"
				+ "    \"consignorAddress\": \"test\",\n"
				+ "    \"consignorAddressId\": "+consignorId+",\n"
				+ "    \"consignorEmail\": \"testunibic@gmail.com\",\n"
				+ "    \"consignorPhone\": \"9971639104\",\n"
				+ "    \"consigneeAddress\": \"sdfv dvervev sc\",\n"
				+ "    \"consigneeAddressId\": 2777053,\n"
				+ "    \"consigneeEmail\": null,\n"
				+ "    \"consigneePhone\": \"12313131313\",\n"
				+ "    \"contents\": \"Chemicals\",\n"
				+ "    \"consignorName\": \"test\",\n"
				+ "    \"consigneeName\": \"Rivigo costumer\",\n"
				+ "    \"consignmentDocumentDtoList\": [\n"
				+ "        {\n"
				+ "            \"document\": \"GST Invoice / Delivery Challan\",\n"
				+ "            \"status\": \"NOT_PICKED_UP\",\n"
				+ "            \"minInvoiceValue\": null,\n"
				+ "            \"documentType\": \"GSTIN number\",\n"
				+ "            \"order\": 99\n"
				+ "        },\n"
				+ "        {\n"
				+ "            \"document\": \"CN consignee copy\",\n"
				+ "            \"status\": \"NOT_PICKED_UP\",\n"
				+ "            \"minInvoiceValue\": null,\n"
				+ "            \"order\": 2\n"
				+ "        },\n"
				+ "        {\n"
				+ "            \"document\": \"CN POD copy\",\n"
				+ "            \"status\": \"NOT_PICKED_UP\",\n"
				+ "            \"minInvoiceValue\": null,\n"
				+ "            \"order\": 1\n"
				+ "        }\n"
				+ "    ],\n"
				+ "    \"packing\": \"Bundle\",\n"
				+ "    \"barcodeType\": \"PRE_PRINTED\",\n"
				+ "    \"barcodes\": [\n"
				+ "        3000037386\n"
				+ "    ],\n"
				+ "    \"isDacc\": null,\n"
				+ "    \"invoices\": [\n"
				+ "        {\n"
				+ "            \"invoiceId\": null,\n"
				+ "            \"invoiceNo\": \"1\",\n"
				+ "            \"invoiceValue\": \"1\",\n"
				+ "            \"eWaybillNumber\": \"\",\n"
				+ "            \"hsnCodes\": null\n"
				+ "        }\n"
				+ "    ],\n"
				+ "    \"volumeDetails\": [\n"
				+ "        {\n"
				+ "            \"unit\": \"IN\",\n"
				+ "            \"breadth\": \"1\",\n"
				+ "            \"height\": \"1\",\n"
				+ "            \"numberOfBoxes\": \"1\",\n"
				+ "            \"length\": \"1\",\n"
				+ "            \"volume\": 0.0006\n"
				+ "        }\n"
				+ "    ],\n"
				+ "    \"valueAddedServicesDTO\": null,\n"
				+ "    \"paymentDetailsDTO\": null,\n"
				+ "    \"gstDetailsDTO\": null,\n"
				+ "    \"taxId\": null,\n"
				+ "    \"taxIdType\": null,\n"
				+ "    \"trackerDTO\": {\n"
				+ "        \"deviceIdType\": \"IP\",\n"
				+ "        \"deviceType\": \"ZOOM_OPS\"\n"
				+ "    },\n"
				+ "    \"openPopupTime\": 1573037386291,\n"
				+ "    \"allIssuesResolved\": true,\n"
				+ "    \"billingEntity\": \"UNIBIC FOODS INDIA PVT LTD.\",\n"
				+ "    \"vehicleNumber\": \"HR55V5525\",\n"
				+ "    \"consignmentCodDodDTO\": null,\n"
				+ "    \"deliveryType\": \"NORMAL\",\n"
				+ "    \"completionStatus\": \"COMPLETE\"\n"
				+ "}";
	}
	public static String loadUnloadCN() {
		return "[\n"
				+ "{\n"
				+ "\"barcode\": \"3000001159\",\n"
				+ "\"cnote\": 3000001129,\n"
				+ "\"createdAt\": \"1555486202152\",\n"
				+ "\"createdById\": 1505,\n"
				+ "\"floorLocationId\": 0,\n"
				+ "\"floorLocationType\": \"ZONE\",\n"
				+ "\"isActive\": true,\n"
				+ "\"isLocationUpdate\": true,\n"
				+ "\"isScanned\": true,\n"
				+ "\"lastUpdatedAt\": \"1555486202152\",\n"
				+ "\"lastUpdatedById\": 1505,\n"
				+ "\"palletId\": null,\n"
				+ "\"scanType\": \"EXPECTED\",\n"
				+ "\"scannedBy\": \"1505\",\n"
				+ "\"taskId\": 1117,\n"
				+ "\"timestamp\": \"1631611429000\",\n"
				+ "\"version\": 0\n"
				+ "}\n"
				+ "]";
	}
	public static String submitCN() {
		return "{\n"
				+ "\"additionalDetails\": {},\n"
				+ "\"errorMessage\": \"Success\",\n"
				+ "\"errors\": {},\n"
				+ "\"payload\": true,\n"
				+ "\"status\": \"SUCCESS\",\n"
				+ "\"statusCode\": 0\n"
				+ "}";
	}
	public static String getFromAddress() {
		return "{\n"
				+ "    \"id\": null,\n"
				+ "    \"client\": {\n"
				+ "        \"id\": "+ClientId+"\n"
				+ "    },\n"
				+ "    \"addressType\": \"PICKUPANDDROP\",\n"
				+ "    \"address\": {\n"
				+ "        \"id\": null,\n"
				+ "        \"detailedAddress\": \"test test test3333395798\",\n"
				+ "        \"pincode\": \""+FromPin+"\",\n"
				+ "        \"state\": \"Delhi\",\n"
				+ "        \"landmark\": null\n"
				+ "    },\n"
				+ "    \"name\": \"test\",\n"
				+ "    \"phoneNumber\": \"9971639104\",\n"
				+ "    \"isAppoinmentDelivery\": false,\n"
				+ "    \"contactPerson\": \"test\",\n"
				+ "    \"status\": \"ACTIVE\",\n"
				+ "    \"organizationId\": null\n"
				+ "}";
		
	}
	public static String getToAddress() {
		return "{\n"
				+ "    \"id\": null,\n"
				+ "    \"client\": {\n"
				+ "        \"id\": "+ClientId+"\n"
				+ "    },\n"
				+ "    \"addressType\": \"PICKUPANDDROP\",\n"
				+ "    \"address\": {\n"
				+ "        \"id\": null,\n"
				+ "        \"detailedAddress\": \"test test test3333395798\",\n"
				+ "        \"pincode\": \""+ToPin+"\",\n"
				+ "        \"state\": \"Delhi\",\n"
				+ "        \"landmark\": null\n"
				+ "    },\n"
				+ "    \"name\": \"test\",\n"
				+ "    \"phoneNumber\": \"9971639104\",\n"
				+ "    \"isAppoinmentDelivery\": false,\n"
				+ "    \"contactPerson\": \"test\",\n"
				+ "    \"status\": \"ACTIVE\",\n"
				+ "    \"organizationId\": null\n"
				+ "}";
		
	}

}
